import { MenuItem, Restaurant, Rider, SmartFindProduct, User } from "./types";
import { randomId } from "./utils";

// Pilot zone: Gombe (Kinshasa)
export const PILOT_ZONE = "Gombe";

export const demoUsers: User[] = [
  {
    id: "u_customer",
    email: "customer@demo.apporte.cd",
    name: "Client Démo",
    role: "customer",
  },
  {
    id: "u_merchant",
    email: "merchant@demo.apporte.cd",
    name: "Restaurant Démo",
    role: "merchant",
    merchantId: "rest_kfc_gombe",
  },
  {
    id: "u_rider",
    email: "rider@demo.apporte.cd",
    name: "Livreur Démo",
    role: "rider",
    riderId: "rider_1",
  },
  {
    id: "u_admin",
    email: "admin@demo.apporte.cd",
    name: "Admin Démo",
    role: "admin",
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "rest_kfc_gombe",
    name: "KFC Gombe",
    cuisine: "Fast Food",
    etaMinutes: 20,
    rating: 4.4,
    imageUrl: "/images/rest_kfc_gombe.jpg",
    zone: PILOT_ZONE,
    latitude: -4.3156,
    longitude: 15.3126,
    isOpen: true,
  },
  {
    id: "rest_pili_pili",
    name: "Pili Pili Grill",
    cuisine: "Grillades",
    etaMinutes: 25,
    rating: 4.5,
    imageUrl: "/images/rest_pili_pili.jpg",
    zone: PILOT_ZONE,
    latitude: -4.322,
    longitude: 15.3075,
    isOpen: true,
  },
  {
    id: "rest_chez_flore",
    name: "Chez Flore",
    cuisine: "Congolais",
    etaMinutes: 28,
    rating: 4.3,
    imageUrl: "/images/rest_chez_flore.jpg",
    zone: PILOT_ZONE,
    latitude: -4.314,
    longitude: 15.297,
    isOpen: true,
  },
  {
    id: "rest_bistrot",
    name: "Le Bistrot de Gombe",
    cuisine: "Bistrot",
    etaMinutes: 22,
    rating: 4.2,
    imageUrl: "/images/rest_bistrot.jpg",
    zone: PILOT_ZONE,
    latitude: -4.309,
    longitude: 15.302,
    isOpen: true,
  },
  {
    id: "rest_maison_poulet",
    name: "Maison du Poulet",
    cuisine: "Poulet",
    etaMinutes: 24,
    rating: 4.1,
    imageUrl: "/images/rest_maison_poulet.jpg",
    zone: PILOT_ZONE,
    latitude: -4.318,
    longitude: 15.315,
    isOpen: true,
  },
  {
    id: "rest_pizza_inn",
    name: "Pizza Inn Gombe",
    cuisine: "Pizza",
    etaMinutes: 26,
    rating: 4.0,
    imageUrl: "/images/rest_pizza_inn.jpg",
    zone: PILOT_ZONE,
    latitude: -4.311,
    longitude: 15.309,
    isOpen: true,
  },
  {
    id: "rest_fuego",
    name: "Chez Fuego Grill",
    cuisine: "Grillades",
    etaMinutes: 23,
    rating: 4.2,
    imageUrl: "/images/rest_fuego.jpg",
    zone: PILOT_ZONE,
    latitude: -4.3195,
    longitude: 15.299,
    isOpen: true,
  },
  {
    id: "rest_orient",
    name: "L'Orient Express",
    cuisine: "Asiatique",
    etaMinutes: 27,
    rating: 4.1,
    imageUrl: "/images/rest_orient.jpg",
    zone: PILOT_ZONE,
    latitude: -4.305,
    longitude: 15.31,
    isOpen: true,
  },
  {
    id: "rest_mamba",
    name: "Chez Mamba",
    cuisine: "Congolais",
    etaMinutes: 25,
    rating: 4.0,
    imageUrl: "/images/rest_mamba.jpg",
    zone: PILOT_ZONE,
    latitude: -4.321,
    longitude: 15.304,
    isOpen: true,
  },
  {
    id: "rest_baguette",
    name: "Baguette & Boteka",
    cuisine: "Boulangerie",
    etaMinutes: 18,
    rating: 4.3,
    imageUrl: "/images/rest_baguette.jpg",
    zone: PILOT_ZONE,
    latitude: -4.317,
    longitude: 15.308,
    isOpen: true,
  },
  {
    id: "rest_sushi",
    name: "Sushi Kin Gombe",
    cuisine: "Sushi",
    etaMinutes: 30,
    rating: 4.2,
    imageUrl: "/images/rest_sushi.jpg",
    zone: PILOT_ZONE,
    latitude: -4.313,
    longitude: 15.319,
    isOpen: true,
  },
  {
    id: "rest_regal",
    name: "Le Régal Congo",
    cuisine: "Congolais",
    etaMinutes: 26,
    rating: 4.1,
    imageUrl: "/images/rest_regal.jpg",
    zone: PILOT_ZONE,
    latitude: -4.312,
    longitude: 15.316,
    isOpen: true,
  },
];

export const menuItems: MenuItem[] = [
  // KFC
  {
    id: "mi_kfc_1",
    restaurantId: "rest_kfc_gombe",
    name: "Bucket Poulet (3 pcs)",
    description: "Poulet croustillant KFC",
    priceUsd: 8,
    available: true,
    imageUrl: "/images/mi_kfc_1.jpg",
    cuisineTag: "Poulet",
  },
  {
    id: "mi_kfc_2",
    restaurantId: "rest_kfc_gombe",
    name: "Burger Zinger",
    description: "Burger poulet épicé",
    priceUsd: 6.5,
    available: true,
    imageUrl: "/images/mi_kfc_2.jpg",
    cuisineTag: "Fast Food",
  },
  // Pili Pili
  {
    id: "mi_pili_1",
    restaurantId: "rest_pili_pili",
    name: "Brochettes de Bœuf",
    description: "Brochettes tendres au pili pili",
    priceUsd: 7,
    available: true,
    imageUrl: "/images/mi_pili_1.jpg",
    cuisineTag: "Grillades",
  },
  {
    id: "mi_pili_2",
    restaurantId: "rest_pili_pili",
    name: "Poisson Braisé",
    description: "Poisson braisé à la congolaise",
    priceUsd: 10,
    available: true,
    imageUrl: "/images/mi_pili_2.jpg",
    cuisineTag: "Poisson",
  },
  // Pizza Inn
  {
    id: "mi_pizza_1",
    restaurantId: "rest_pizza_inn",
    name: "Pizza Margherita (M)",
    description: "Classique, mozzarella et basilic",
    priceUsd: 9,
    available: true,
    imageUrl: "/images/mi_pizza_1.jpg",
    cuisineTag: "Pizza",
  },
  {
    id: "mi_pizza_2",
    restaurantId: "rest_pizza_inn",
    name: "Pizza Poulet (M)",
    description: "Poulet, oignons, poivrons",
    priceUsd: 11,
    available: true,
    imageUrl: "/images/mi_pizza_2.jpg",
    cuisineTag: "Pizza",
  },
  // Maison du Poulet
  {
    id: "mi_poulet_1",
    restaurantId: "rest_maison_poulet",
    name: "Poulet Grillé",
    description: "Demi poulet grillé",
    priceUsd: 12,
    available: true,
    imageUrl: "/images/mi_poulet_1.jpg",
    cuisineTag: "Poulet",
  },
  // Chez Flore
  {
    id: "mi_flore_1",
    restaurantId: "rest_chez_flore",
    name: "Saka-Saka",
    description: "Feuilles de manioc, arachides",
    priceUsd: 5,
    available: true,
    imageUrl: "/images/mi_flore_1.jpg",
    cuisineTag: "Congolais",
  },
  // Bistrot
  {
    id: "mi_bistrot_1",
    restaurantId: "rest_bistrot",
    name: "Steak Frites",
    description: "Steak, frites et salade",
    priceUsd: 13,
    available: true,
    imageUrl: "/images/mi_bistrot_1.jpg",
    cuisineTag: "Bistrot",
  },
  {
    id: "mi_orient_1",
    restaurantId: "rest_orient",
    name: "Nouilles sautées",
    description: "Légumes, soja et nouilles croustillantes",
    priceUsd: 9,
    available: true,
    imageUrl: "/images/sushi.jpg",
    cuisineTag: "Asiatique",
  },
  {
    id: "mi_orient_2",
    restaurantId: "rest_orient",
    name: "Poisson à la vapeur",
    description: "Gingembre, ciboule et riz",
    priceUsd: 12,
    available: true,
    imageUrl: "/images/fish.jpg",
    cuisineTag: "Asiatique",
  },
  {
    id: "mi_fuego_1",
    restaurantId: "rest_fuego",
    name: "Poulet braisé piquant",
    description: "Mariné au pili pili, servi avec frites",
    priceUsd: 11,
    available: true,
    imageUrl: "/images/chicken.jpg",
    cuisineTag: "Grillades",
  },
  {
    id: "mi_fuego_2",
    restaurantId: "rest_fuego",
    name: "Brochettes mixtes",
    description: "Bœuf et poulet, sauce maison",
    priceUsd: 8,
    available: true,
    imageUrl: "/images/burger.jpg",
    cuisineTag: "Grillades",
  },
  {
    id: "mi_mamba_1",
    restaurantId: "rest_mamba",
    name: "Poulet moambé",
    description: "Sauce arachide, riz blanc",
    priceUsd: 10,
    available: true,
    imageUrl: "/images/chicken.jpg",
    cuisineTag: "Congolais",
  },
  {
    id: "mi_mamba_2",
    restaurantId: "rest_mamba",
    name: "Poisson braisé",
    description: "Entier, piment et plantain",
    priceUsd: 13,
    available: true,
    imageUrl: "/images/fish.jpg",
    cuisineTag: "Congolais",
  },
  {
    id: "mi_baguette_1",
    restaurantId: "rest_baguette",
    name: "Baguette beurre",
    description: "Sortie du four",
    priceUsd: 1.5,
    available: true,
    imageUrl: "/images/bread.jpg",
    cuisineTag: "Boulangerie",
  },
  {
    id: "mi_baguette_2",
    restaurantId: "rest_baguette",
    name: "Sandwich poulet",
    description: "Baguette, poulet grillé, crudités",
    priceUsd: 5,
    available: true,
    imageUrl: "/images/burger.jpg",
    cuisineTag: "Boulangerie",
  },
  {
    id: "mi_sushi_1",
    restaurantId: "rest_sushi",
    name: "Assortiment maki",
    description: "8 pièces, saumon et avocat",
    priceUsd: 14,
    available: true,
    imageUrl: "/images/sushi.jpg",
    cuisineTag: "Sushi",
  },
  {
    id: "mi_sushi_2",
    restaurantId: "rest_sushi",
    name: "Nigiri saumon",
    description: "4 pièces",
    priceUsd: 11,
    available: true,
    imageUrl: "/images/sushi.jpg",
    cuisineTag: "Sushi",
  },
  {
    id: "mi_regal_1",
    restaurantId: "rest_regal",
    name: "Liboke de poisson",
    description: "Cuit à la vapeur dans des feuilles",
    priceUsd: 12,
    available: true,
    imageUrl: "/images/fish.jpg",
    cuisineTag: "Congolais",
  },
  {
    id: "mi_regal_2",
    restaurantId: "rest_regal",
    name: "Poulet à la braise",
    description: "Demi poulet, piment et frites",
    priceUsd: 11,
    available: true,
    imageUrl: "/images/chicken.jpg",
    cuisineTag: "Congolais",
  },
];

export const smartFinds: SmartFindProduct[] = [
  {
    id: "sf_powerbank",
    name: "Power bank 20,000 mAh",
    description: "Recharge ton téléphone partout",
    priceUsd: 18,
    stock: 20,
    category: "Mobile & Tech",
    imageUrl: "/images/sf_powerbank.jpg",
    tags: ["charge rapide", "USB-C"],
  },
  {
    id: "sf_compressor",
    name: "Compresseur portable voiture",
    description: "Gonfle tes pneus en minutes",
    priceUsd: 25,
    stock: 10,
    category: "Automotive",
    imageUrl: "/images/sf_compressor.jpg",
    tags: ["12V", "LED"],
  },
  {
    id: "sf_lamp",
    name: "Lampe rechargeable",
    description: "Éclairage d'urgence",
    priceUsd: 12,
    stock: 30,
    category: "Home",
    imageUrl: "/images/sf_lamp.jpg",
  },
  {
    id: "sf_fast_charger",
    name: "Chargeur rapide 20W",
    description: "Charge express USB-C",
    priceUsd: 9,
    stock: 40,
    category: "Mobile & Tech",
    imageUrl: "/images/sf_fast_charger.jpg",
  },
  {
    id: "sf_phone_holder",
    name: "Support téléphone voiture",
    description: "Stable, compatible universel",
    priceUsd: 7,
    stock: 25,
    category: "Automotive",
    imageUrl: "/images/sf_phone_holder.jpg",
  },
  {
    id: "sf_fan",
    name: "Ventilateur portable",
    description: "USB, compact et puissant",
    priceUsd: 14,
    stock: 15,
    category: "Lifestyle",
    imageUrl: "/images/sf_fan.jpg",
  },
  {
    id: "sf_jump_starter",
    name: "Batterie de démarrage",
    description: "Démarre ta voiture rapidement",
    priceUsd: 58,
    stock: 8,
    category: "Automotive",
    imageUrl: "/images/sf_jump_starter.jpg",
  },
  {
    id: "sf_emergency_light",
    name: "Lampe d'urgence LED",
    description: "Signalisation de nuit",
    priceUsd: 10,
    stock: 20,
    category: "Automotive",
    imageUrl: "/images/sf_emergency_light.jpg",
  },
];

export const riders: Rider[] = [
  {
    id: "rider_1",
    name: "Jean",
    status: "online",
    reliabilityPercent: 98,
    latitude: -4.314,
    longitude: 15.312,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_2",
    name: "Patrick",
    status: "online",
    reliabilityPercent: 96,
    latitude: -4.318,
    longitude: 15.305,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_3",
    name: "Martha",
    status: "online",
    reliabilityPercent: 92,
    latitude: -4.321,
    longitude: 15.309,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_4",
    name: "Junior",
    status: "online",
    reliabilityPercent: 90,
    latitude: -4.312,
    longitude: 15.298,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_5",
    name: "Amina",
    status: "offline",
    reliabilityPercent: 95,
    latitude: -4.305,
    longitude: 15.315,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_6",
    name: "Michel",
    status: "online",
    reliabilityPercent: 91,
    latitude: -4.316,
    longitude: 15.301,
    earningsTodayUsd: 0,
  },
];

// Helper to pick items by restaurant for quick menus
export function getMenuForRestaurant(restaurantId: string): MenuItem[] {
  return menuItems.filter((m) => m.restaurantId === restaurantId);
}

