import { MenuItem, Restaurant, Rider, SmartFindProduct, User } from "./types";
import { randomId } from "./utils";

// Pilot zone: Gombe (Kinshasa)
export const PILOT_ZONE = "Gombe";

export const demoUsers: User[] = [
  {
    id: "u_customer",
    email: "customer@demo.apporte.cd",
    name: "Client Démo",
    role: "customer",
  },
  {
    id: "u_merchant",
    email: "merchant@demo.apporte.cd",
    name: "Restaurant Démo",
    role: "merchant",
    merchantId: "rest_kfc_gombe",
  },
  {
    id: "u_rider",
    email: "rider@demo.apporte.cd",
    name: "Livreur Démo",
    role: "rider",
    riderId: "rider_1",
  },
  {
    id: "u_admin",
    email: "admin@demo.apporte.cd",
    name: "Admin Démo",
    role: "admin",
  },
];

export const restaurants: Restaurant[] = [
  {
    id: "rest_kfc_gombe",
    name: "KFC Gombe",
    cuisine: "Fast Food",
    etaMinutes: 20,
    rating: 4.4,
    imageUrl: "/images/rest_kfc_gombe.jpg",
    zone: PILOT_ZONE,
    latitude: -4.3156,
    longitude: 15.3126,
    isOpen: true,
  },
  {
    id: "rest_pili_pili",
    name: "Pili Pili Grill",
    cuisine: "Grillades",
    etaMinutes: 25,
    rating: 4.5,
    imageUrl: "/images/rest_pili_pili.jpg",
    zone: PILOT_ZONE,
    latitude: -4.322,
    longitude: 15.3075,
    isOpen: true,
  },
  {
    id: "rest_chez_flore",
    name: "Chez Flore",
    cuisine: "Congolais",
    etaMinutes: 28,
    rating: 4.3,
    imageUrl: "/images/rest_chez_flore.jpg",
    zone: PILOT_ZONE,
    latitude: -4.314,
    longitude: 15.297,
    isOpen: true,
  },
  {
    id: "rest_bistrot",
    name: "Le Bistrot de Gombe",
    cuisine: "Bistrot",
    etaMinutes: 22,
    rating: 4.2,
    imageUrl: "/images/rest_bistrot.jpg",
    zone: PILOT_ZONE,
    latitude: -4.309,
    longitude: 15.302,
    isOpen: true,
  },
  {
    id: "rest_maison_poulet",
    name: "Maison du Poulet",
    cuisine: "Poulet",
    etaMinutes: 24,
    rating: 4.1,
    imageUrl: "/images/rest_maison_poulet.jpg",
    zone: PILOT_ZONE,
    latitude: -4.318,
    longitude: 15.315,
    isOpen: true,
  },
  {
    id: "rest_pizza_inn",
    name: "Pizza Inn Gombe",
    cuisine: "Pizza",
    etaMinutes: 26,
    rating: 4.0,
    imageUrl: "/images/rest_pizza_inn.jpg",
    zone: PILOT_ZONE,
    latitude: -4.311,
    longitude: 15.309,
    isOpen: true,
  },
  {
    id: "rest_fuego",
    name: "Chez Fuego Grill",
    cuisine: "Grillades",
    etaMinutes: 23,
    rating: 4.2,
    imageUrl: "/images/rest_fuego.jpg",
    zone: PILOT_ZONE,
    latitude: -4.3195,
    longitude: 15.299,
    isOpen: true,
  },
  {
    id: "rest_orient",
    name: "L'Orient Express",
    cuisine: "Asiatique",
    etaMinutes: 27,
    rating: 4.1,
    imageUrl: "/images/rest_orient.jpg",
    zone: PILOT_ZONE,
    latitude: -4.305,
    longitude: 15.31,
    isOpen: true,
  },
  {
    id: "rest_mamba",
    name: "Chez Mamba",
    cuisine: "Congolais",
    etaMinutes: 25,
    rating: 4.0,
    imageUrl: "/images/rest_mamba.jpg",
    zone: PILOT_ZONE,
    latitude: -4.321,
    longitude: 15.304,
    isOpen: true,
  },
  {
    id: "rest_baguette",
    name: "Baguette & Boteka",
    cuisine: "Boulangerie",
    etaMinutes: 18,
    rating: 4.3,
    imageUrl: "/images/rest_baguette.jpg",
    zone: PILOT_ZONE,
    latitude: -4.317,
    longitude: 15.308,
    isOpen: true,
  },
  {
    id: "rest_sushi",
    name: "Sushi Kin Gombe",
    cuisine: "Sushi",
    etaMinutes: 30,
    rating: 4.2,
    imageUrl: "/images/rest_sushi.jpg",
    zone: PILOT_ZONE,
    latitude: -4.313,
    longitude: 15.319,
    isOpen: true,
  },
  {
    id: "rest_regal",
    name: "Le Régal Congo",
    cuisine: "Congolais",
    etaMinutes: 26,
    rating: 4.1,
    imageUrl: "/images/rest_regal.jpg",
    zone: PILOT_ZONE,
    latitude: -4.312,
    longitude: 15.316,
    isOpen: true,
  },
];

export const menuItems: MenuItem[] = [
  { id: "mi_kfc_1", restaurantId: "rest_kfc_gombe", name: "Bucket Poulet (3 pcs)", description: "Poulet croustillant KFC", priceUsd: 8, available: true, imageUrl: "/images/mi_kfc_1.jpg", cuisineTag: "Poulet" },
  { id: "mi_kfc_2", restaurantId: "rest_kfc_gombe", name: "Burger Zinger", description: "Burger poulet épicé", priceUsd: 6.5, available: true, imageUrl: "/images/mi_kfc_2.jpg", cuisineTag: "Fast Food" },
  { id: "mi_pili_1", restaurantId: "rest_pili_pili", name: "Brochettes de Bœuf", description: "Brochettes tendres au pili pili", priceUsd: 7, available: true, imageUrl: "/images/mi_pili_1.jpg", cuisineTag: "Grillades" },
  { id: "mi_pili_2", restaurantId: "rest_pili_pili", name: "Poisson Braisé", description: "Poisson braisé à la congolaise", priceUsd: 10, available: true, imageUrl: "/images/mi_pili_2.jpg", cuisineTag: "Poisson" },
  { id: "mi_pizza_1", restaurantId: "rest_pizza_inn", name: "Pizza Margherita (M)", description: "Classique, mozzarella et basilic", priceUsd: 9, available: true, imageUrl: "/images/mi_pizza_1.jpg", cuisineTag: "Pizza" },
  { id: "mi_pizza_2", restaurantId: "rest_pizza_inn", name: "Pizza Poulet (M)", description: "Poulet, oignons, poivrons", priceUsd: 11, available: true, imageUrl: "/images/mi_pizza_2.jpg", cuisineTag: "Pizza" },
  { id: "mi_poulet_1", restaurantId: "rest_maison_poulet", name: "Poulet Grillé", description: "Demi poulet grillé", priceUsd: 12, available: true, imageUrl: "/images/mi_poulet_1.jpg", cuisineTag: "Poulet" },
  { id: "mi_flore_1", restaurantId: "rest_chez_flore", name: "Saka-Saka", description: "Feuilles de manioc, arachides", priceUsd: 5, available: true, imageUrl: "/images/mi_flore_1.jpg", cuisineTag: "Congolais" },
  { id: "mi_bistrot_1", restaurantId: "rest_bistrot", name: "Steak Frites", description: "Steak, frites et salade", priceUsd: 13, available: true, imageUrl: "/images/mi_bistrot_1.jpg", cuisineTag: "Bistrot" },
  { id: "mi_kfc_3", restaurantId: "rest_kfc_gombe", name: "Twister Wrap", description: "Tortilla, filets de poulet croustillants, crudités et sauce", priceUsd: 6.0, available: true, imageUrl: "/images/mi_kfc_3.jpg", cuisineTag: "Fast Food" },
  { id: "mi_kfc_4", restaurantId: "rest_kfc_gombe", name: "Ailes épicées (6 pcs)", description: "Ailes de poulet épicées et croustillantes", priceUsd: 6.0, available: true, imageUrl: "/images/mi_kfc_4.jpg", cuisineTag: "Poulet" },
  { id: "mi_kfc_5", restaurantId: "rest_kfc_gombe", name: "Bouchées de poulet croustillant", description: "Petits morceaux de poulet pané, sauce au choix", priceUsd: 5.0, available: true, imageUrl: "/images/mi_kfc_5.jpg", cuisineTag: "Poulet" },
  { id: "mi_kfc_6", restaurantId: "rest_kfc_gombe", name: "Frites (grande portion)", description: "Frites dorées et salées", priceUsd: 2.5, available: true, imageUrl: "/images/mi_kfc_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_pili_3", restaurantId: "rest_pili_pili", name: "Poulet braisé pili pili", description: "Demi-poulet mariné, braisé au charbon, piment maison", priceUsd: 10.0, available: true, imageUrl: "/images/mi_pili_3.jpg", cuisineTag: "Grillades" },
  { id: "mi_pili_4", restaurantId: "rest_pili_pili", name: "Ntaba (chèvre grillée)", description: "Viande de chèvre grillée, oignons et piment", priceUsd: 9.0, available: true, imageUrl: "/images/mi_pili_4.jpg", cuisineTag: "Grillades" },
  { id: "mi_pili_5", restaurantId: "rest_pili_pili", name: "Makemba frits", description: "Bananes plantains frites", priceUsd: 3.0, available: true, imageUrl: "/images/mi_pili_5.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_pili_6", restaurantId: "rest_pili_pili", name: "Chikwangue", description: "Pain de manioc traditionnel", priceUsd: 1.5, available: true, imageUrl: "/images/mi_pili_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_pili_7", restaurantId: "rest_pili_pili", name: "Primus 72 cl", description: "Bière blonde congolaise", priceUsd: 2.5, available: true, imageUrl: "/images/mi_pili_7.jpg", cuisineTag: "Boisson" },
  { id: "mi_flore_2", restaurantId: "rest_chez_flore", name: "Poulet à la moambe", description: "Poulet mijoté dans la sauce noix de palme", priceUsd: 9.0, available: true, imageUrl: "/images/mi_flore_2.jpg", cuisineTag: "Congolais" },
  { id: "mi_flore_3", restaurantId: "rest_chez_flore", name: "Liboke de poisson", description: "Poisson cuit en feuilles de bananier, épices", priceUsd: 11.0, available: true, imageUrl: "/images/mi_flore_3.jpg", cuisineTag: "Congolais" },
  { id: "mi_flore_4", restaurantId: "rest_chez_flore", name: "Fumbwa", description: "Feuilles de fumbwa à l'arachide et au poisson fumé", priceUsd: 7.0, available: true, imageUrl: "/images/mi_flore_4.jpg", cuisineTag: "Congolais" },
  { id: "mi_flore_5", restaurantId: "rest_chez_flore", name: "Madesu", description: "Haricots rouges mijotés à la tomate", priceUsd: 4.0, available: true, imageUrl: "/images/mi_flore_5.jpg", cuisineTag: "Congolais" },
  { id: "mi_flore_6", restaurantId: "rest_chez_flore", name: "Fufu", description: "Pâte de manioc et maïs", priceUsd: 1.5, available: true, imageUrl: "/images/mi_flore_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_flore_7", restaurantId: "rest_chez_flore", name: "Jus de bissap", description: "Infusion d'hibiscus maison, bien fraîche", priceUsd: 2.0, available: true, imageUrl: "/images/mi_flore_7.jpg", cuisineTag: "Boisson" },
  { id: "mi_bistrot_2", restaurantId: "rest_bistrot", name: "Croque-monsieur", description: "Jambon, emmental, béchamel, salade verte", priceUsd: 7.0, available: true, imageUrl: "/images/mi_bistrot_2.jpg", cuisineTag: "Bistrot" },
  { id: "mi_bistrot_3", restaurantId: "rest_bistrot", name: "Salade César", description: "Poulet grillé, parmesan, croûtons, sauce César", priceUsd: 9.0, available: true, imageUrl: "/images/mi_bistrot_3.jpg", cuisineTag: "Bistrot" },
  { id: "mi_bistrot_4", restaurantId: "rest_bistrot", name: "Burger du Bistrot", description: "Bœuf haché, cheddar, oignons caramélisés, frites", priceUsd: 12.0, available: true, imageUrl: "/images/mi_bistrot_4.jpg", cuisineTag: "Bistrot" },
  { id: "mi_bistrot_5", restaurantId: "rest_bistrot", name: "Filet de capitaine", description: "Capitaine poêlé, sauce beurre citronné, riz", priceUsd: 16.0, available: true, imageUrl: "/images/mi_bistrot_5.jpg", cuisineTag: "Poisson" },
  { id: "mi_bistrot_7", restaurantId: "rest_bistrot", name: "Crème brûlée", description: "Crème vanille, caramel croquant", priceUsd: 5.0, available: true, imageUrl: "/images/mi_bistrot_7.jpg", cuisineTag: "Dessert" },
  { id: "mi_poulet_2", restaurantId: "rest_maison_poulet", name: "Poulet entier braisé", description: "Poulet entier braisé, pour 3 à 4 personnes", priceUsd: 20.0, available: true, imageUrl: "/images/mi_poulet_2.jpg", cuisineTag: "Poulet" },
  { id: "mi_poulet_3", restaurantId: "rest_maison_poulet", name: "Ailes de poulet grillées (8 pcs)", description: "Ailes marinées, grillées au feu de bois", priceUsd: 7.0, available: true, imageUrl: "/images/mi_poulet_3.jpg", cuisineTag: "Poulet" },
  { id: "mi_poulet_4", restaurantId: "rest_maison_poulet", name: "Brochettes de poulet", description: "Trois brochettes, oignons et poivrons", priceUsd: 7.0, available: true, imageUrl: "/images/mi_poulet_4.jpg", cuisineTag: "Poulet" },
  { id: "mi_poulet_5", restaurantId: "rest_maison_poulet", name: "Frites de manioc", description: "Manioc frit croustillant", priceUsd: 3.0, available: true, imageUrl: "/images/mi_poulet_5.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_poulet_6", restaurantId: "rest_maison_poulet", name: "Riz blanc", description: "Riz parfumé nature", priceUsd: 2.0, available: true, imageUrl: "/images/mi_poulet_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_pizza_3", restaurantId: "rest_pizza_inn", name: "Pizza Pepperoni (M)", description: "Sauce tomate, mozzarella, pepperoni", priceUsd: 11.0, available: true, imageUrl: "/images/mi_pizza_3.jpg", cuisineTag: "Pizza" },
  { id: "mi_pizza_4", restaurantId: "rest_pizza_inn", name: "Pizza Quatre fromages (M)", description: "Mozzarella, gorgonzola, parmesan, chèvre", priceUsd: 12.0, available: true, imageUrl: "/images/mi_pizza_4.jpg", cuisineTag: "Pizza" },
  { id: "mi_pizza_5", restaurantId: "rest_pizza_inn", name: "Pizza Végétarienne (M)", description: "Poivrons, champignons, oignons, olives", priceUsd: 10.0, available: true, imageUrl: "/images/mi_pizza_5.jpg", cuisineTag: "Pizza" },
  { id: "mi_pizza_6", restaurantId: "rest_pizza_inn", name: "Pizza Hawaïenne (M)", description: "Jambon, ananas, mozzarella", priceUsd: 11.0, available: true, imageUrl: "/images/mi_pizza_6.jpg", cuisineTag: "Pizza" },
  { id: "mi_pizza_7", restaurantId: "rest_pizza_inn", name: "Pain à l'ail", description: "Pain grillé, beurre à l'ail et persil", priceUsd: 4.0, available: true, imageUrl: "/images/mi_pizza_7.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_fuego_1", restaurantId: "rest_fuego", name: "Entrecôte grillée", description: "Entrecôte 300 g, frites maison, sauce poivre", priceUsd: 18.0, available: true, imageUrl: "/images/mi_fuego_1.jpg", cuisineTag: "Grillades" },
  { id: "mi_fuego_2", restaurantId: "rest_fuego", name: "Brochettes mixtes", description: "Bœuf, poulet et saucisse, légumes grillés", priceUsd: 10.0, available: true, imageUrl: "/images/mi_fuego_2.jpg", cuisineTag: "Grillades" },
  { id: "mi_fuego_3", restaurantId: "rest_fuego", name: "Côtelettes d'agneau", description: "Quatre côtelettes, romarin, pommes sautées", priceUsd: 17.0, available: true, imageUrl: "/images/mi_fuego_3.jpg", cuisineTag: "Grillades" },
  { id: "mi_fuego_4", restaurantId: "rest_fuego", name: "Poulet grillé au citron", description: "Demi-poulet mariné citron et ail", priceUsd: 11.0, available: true, imageUrl: "/images/mi_fuego_4.jpg", cuisineTag: "Poulet" },
  { id: "mi_fuego_5", restaurantId: "rest_fuego", name: "Tilapia braisé", description: "Tilapia entier braisé, oignons, piment", priceUsd: 13.0, available: true, imageUrl: "/images/mi_fuego_5.jpg", cuisineTag: "Poisson" },
  { id: "mi_fuego_6", restaurantId: "rest_fuego", name: "Saucisses grillées", description: "Saucisses de bœuf grillées, moutarde", priceUsd: 7.0, available: true, imageUrl: "/images/mi_fuego_6.jpg", cuisineTag: "Grillades" },
  { id: "mi_fuego_7", restaurantId: "rest_fuego", name: "Maïs grillé", description: "Épis de maïs grillés au charbon", priceUsd: 2.5, available: true, imageUrl: "/images/mi_fuego_7.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_orient_1", restaurantId: "rest_orient", name: "Nouilles sautées au poulet", description: "Nouilles de blé, poulet, légumes, sauce soja", priceUsd: 9.0, available: true, imageUrl: "/images/mi_orient_1.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_2", restaurantId: "rest_orient", name: "Riz cantonais", description: "Riz sauté, œuf, petits pois, jambon", priceUsd: 8.0, available: true, imageUrl: "/images/mi_orient_2.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_3", restaurantId: "rest_orient", name: "Nems (6 pcs)", description: "Rouleaux croustillants au porc, sauce aigre-douce", priceUsd: 6.0, available: true, imageUrl: "/images/mi_orient_3.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_4", restaurantId: "rest_orient", name: "Poulet Général Tao", description: "Poulet croustillant, sauce sucrée-épicée, riz", priceUsd: 11.0, available: true, imageUrl: "/images/mi_orient_4.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_5", restaurantId: "rest_orient", name: "Bœuf sauté aux oignons", description: "Émincé de bœuf, oignons, gingembre", priceUsd: 12.0, available: true, imageUrl: "/images/mi_orient_5.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_6", restaurantId: "rest_orient", name: "Soupe wonton", description: "Raviolis aux crevettes dans un bouillon clair", priceUsd: 7.0, available: true, imageUrl: "/images/mi_orient_6.jpg", cuisineTag: "Asiatique" },
  { id: "mi_orient_7", restaurantId: "rest_orient", name: "Crevettes sautées à l'ail", description: "Crevettes, ail, piment doux, riz", priceUsd: 14.0, available: true, imageUrl: "/images/mi_orient_7.jpg", cuisineTag: "Asiatique" },
  { id: "mi_mamba_1", restaurantId: "rest_mamba", name: "Pondu au poisson salé", description: "Feuilles de manioc pilées, makayabu, huile de palme", priceUsd: 8.0, available: true, imageUrl: "/images/mi_mamba_1.jpg", cuisineTag: "Congolais" },
  { id: "mi_mamba_2", restaurantId: "rest_mamba", name: "Poulet mwambe", description: "Poulet fermier en sauce moambe, riz", priceUsd: 10.0, available: true, imageUrl: "/images/mi_mamba_2.jpg", cuisineTag: "Congolais" },
  { id: "mi_mamba_3", restaurantId: "rest_mamba", name: "Liboke de capitaine", description: "Capitaine en papillote de feuilles de bananier", priceUsd: 13.0, available: true, imageUrl: "/images/mi_mamba_3.jpg", cuisineTag: "Poisson" },
  { id: "mi_mamba_5", restaurantId: "rest_mamba", name: "Ngulu (porc braisé)", description: "Porc braisé, piment et oignons", priceUsd: 10.0, available: true, imageUrl: "/images/mi_mamba_5.jpg", cuisineTag: "Congolais" },
  { id: "mi_mamba_6", restaurantId: "rest_mamba", name: "Kwanga", description: "Pain de manioc fermenté", priceUsd: 1.5, available: true, imageUrl: "/images/mi_mamba_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_mamba_7", restaurantId: "rest_mamba", name: "Loso na madesu", description: "Riz et haricots mijotés", priceUsd: 4.0, available: true, imageUrl: "/images/mi_mamba_7.jpg", cuisineTag: "Congolais" },
  { id: "mi_baguette_1", restaurantId: "rest_baguette", name: "Croissant pur beurre", description: "Croissant feuilleté du jour", priceUsd: 1.5, available: true, imageUrl: "/images/mi_baguette_1.jpg", cuisineTag: "Boulangerie" },
  { id: "mi_baguette_2", restaurantId: "rest_baguette", name: "Pain au chocolat", description: "Viennoiserie au chocolat", priceUsd: 2.0, available: true, imageUrl: "/images/mi_baguette_2.jpg", cuisineTag: "Boulangerie" },
  { id: "mi_baguette_3", restaurantId: "rest_baguette", name: "Baguette tradition", description: "Baguette croustillante cuite sur place", priceUsd: 1.0, available: true, imageUrl: "/images/mi_baguette_3.jpg", cuisineTag: "Boulangerie" },
  { id: "mi_baguette_4", restaurantId: "rest_baguette", name: "Sandwich jambon-beurre", description: "Baguette, jambon, beurre", priceUsd: 4.0, available: true, imageUrl: "/images/mi_baguette_4.jpg", cuisineTag: "Sandwich" },
  { id: "mi_baguette_5", restaurantId: "rest_baguette", name: "Sandwich poulet crudités", description: "Poulet, salade, tomate, mayonnaise", priceUsd: 5.0, available: true, imageUrl: "/images/mi_baguette_5.jpg", cuisineTag: "Sandwich" },
  { id: "mi_baguette_7", restaurantId: "rest_baguette", name: "Quiche lorraine", description: "Part de quiche lardons et fromage", priceUsd: 4.5, available: true, imageUrl: "/images/mi_baguette_7.jpg", cuisineTag: "Boulangerie" },
  { id: "mi_baguette_8", restaurantId: "rest_baguette", name: "Café au lait", description: "Café arabica et lait chaud", priceUsd: 2.5, available: true, imageUrl: "/images/mi_baguette_8.jpg", cuisineTag: "Boisson" },
  { id: "mi_sushi_1", restaurantId: "rest_sushi", name: "Plateau mixte (18 pcs)", description: "Makis, california et nigiris assortis", priceUsd: 25.0, available: true, imageUrl: "/images/mi_sushi_1.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_2", restaurantId: "rest_sushi", name: "California roll (8 pcs)", description: "Surimi, avocat, concombre, sésame", priceUsd: 10.0, available: true, imageUrl: "/images/mi_sushi_2.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_3", restaurantId: "rest_sushi", name: "Maki saumon (6 pcs)", description: "Saumon frais, riz vinaigré, nori", priceUsd: 7.0, available: true, imageUrl: "/images/mi_sushi_3.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_4", restaurantId: "rest_sushi", name: "Sashimi saumon (8 pcs)", description: "Tranches de saumon frais", priceUsd: 14.0, available: true, imageUrl: "/images/mi_sushi_4.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_5", restaurantId: "rest_sushi", name: "Nigiri assortis (6 pcs)", description: "Saumon, thon et crevette", priceUsd: 12.0, available: true, imageUrl: "/images/mi_sushi_5.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_6", restaurantId: "rest_sushi", name: "Tempura de crevettes", description: "Crevettes en beignet léger, sauce tentsuyu", priceUsd: 11.0, available: true, imageUrl: "/images/mi_sushi_6.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_7", restaurantId: "rest_sushi", name: "Soupe miso", description: "Tofu, wakamé, ciboule", priceUsd: 4.0, available: true, imageUrl: "/images/mi_sushi_7.jpg", cuisineTag: "Sushi" },
  { id: "mi_sushi_8", restaurantId: "rest_sushi", name: "Edamame", description: "Fèves de soja, fleur de sel", priceUsd: 4.0, available: true, imageUrl: "/images/mi_sushi_8.jpg", cuisineTag: "Sushi" },
  { id: "mi_regal_1", restaurantId: "rest_regal", name: "Mbisi ya kalinga", description: "Poisson braisé entier, sauce tomate pimentée", priceUsd: 12.0, available: true, imageUrl: "/images/mi_regal_1.jpg", cuisineTag: "Poisson" },
  { id: "mi_regal_2", restaurantId: "rest_regal", name: "Poulet à la moambe", description: "Poulet en sauce noix de palme, riz ou fufu", priceUsd: 10.0, available: true, imageUrl: "/images/mi_regal_2.jpg", cuisineTag: "Congolais" },
  { id: "mi_regal_4", restaurantId: "rest_regal", name: "Fumbwa aux crevettes", description: "Fumbwa, pâte d'arachide, crevettes séchées", priceUsd: 8.0, available: true, imageUrl: "/images/mi_regal_4.jpg", cuisineTag: "Congolais" },
  { id: "mi_regal_5", restaurantId: "rest_regal", name: "Chèvre en sauce", description: "Ragoût de chèvre tomate et oignons", priceUsd: 10.0, available: true, imageUrl: "/images/mi_regal_5.jpg", cuisineTag: "Congolais" },
  { id: "mi_regal_6", restaurantId: "rest_regal", name: "Bananes plantains braisées", description: "Plantains mûrs grillés au charbon", priceUsd: 3.0, available: true, imageUrl: "/images/mi_regal_6.jpg", cuisineTag: "Accompagnement" },
  { id: "mi_regal_7", restaurantId: "rest_regal", name: "Jus de maracuja", description: "Fruit de la passion pressé", priceUsd: 2.0, available: true, imageUrl: "/images/mi_regal_7.jpg", cuisineTag: "Boisson" },
];

export const smartFinds: SmartFindProduct[] = [
  {
    id: "sf_powerbank",
    name: "Power bank 20,000 mAh",
    description: "Recharge ton téléphone partout",
    priceUsd: 18,
    stock: 20,
    category: "Mobile & Tech",
    imageUrl: "/images/sf_powerbank.jpg",
    tags: ["charge rapide", "USB-C"],
  },
  {
    id: "sf_compressor",
    name: "Compresseur portable voiture",
    description: "Gonfle tes pneus en minutes",
    priceUsd: 25,
    stock: 10,
    category: "Automotive",
    imageUrl: "/images/sf_compressor.jpg",
    tags: ["12V", "LED"],
  },
  {
    id: "sf_lamp",
    name: "Lampe rechargeable",
    description: "Éclairage d'urgence",
    priceUsd: 12,
    stock: 30,
    category: "Home",
    imageUrl: "/images/sf_lamp.jpg",
  },
  {
    id: "sf_fast_charger",
    name: "Chargeur rapide 20W",
    description: "Charge express USB-C",
    priceUsd: 9,
    stock: 40,
    category: "Mobile & Tech",
    imageUrl: "/images/sf_fast_charger.jpg",
  },
  {
    id: "sf_phone_holder",
    name: "Support téléphone voiture",
    description: "Stable, compatible universel",
    priceUsd: 7,
    stock: 25,
    category: "Automotive",
    imageUrl: "/images/sf_phone_holder.jpg",
  },
  {
    id: "sf_fan",
    name: "Ventilateur portable",
    description: "USB, compact et puissant",
    priceUsd: 14,
    stock: 15,
    category: "Lifestyle",
    imageUrl: "/images/sf_fan.jpg",
  },
  {
    id: "sf_jump_starter",
    name: "Batterie de démarrage",
    description: "Démarre ta voiture rapidement",
    priceUsd: 58,
    stock: 8,
    category: "Automotive",
    imageUrl: "/images/sf_jump_starter.jpg",
  },
  {
    id: "sf_emergency_light",
    name: "Lampe d'urgence LED",
    description: "Signalisation de nuit",
    priceUsd: 10,
    stock: 20,
    category: "Automotive",
    imageUrl: "/images/sf_emergency_light.jpg",
  },
];

export const riders: Rider[] = [
  {
    id: "rider_1",
    name: "Jean",
    status: "online",
    reliabilityPercent: 98,
    latitude: -4.314,
    longitude: 15.312,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_2",
    name: "Patrick",
    status: "online",
    reliabilityPercent: 96,
    latitude: -4.318,
    longitude: 15.305,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_3",
    name: "Martha",
    status: "online",
    reliabilityPercent: 92,
    latitude: -4.321,
    longitude: 15.309,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_4",
    name: "Junior",
    status: "online",
    reliabilityPercent: 90,
    latitude: -4.312,
    longitude: 15.298,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_5",
    name: "Amina",
    status: "offline",
    reliabilityPercent: 95,
    latitude: -4.305,
    longitude: 15.315,
    earningsTodayUsd: 0,
  },
  {
    id: "rider_6",
    name: "Michel",
    status: "online",
    reliabilityPercent: 91,
    latitude: -4.316,
    longitude: 15.301,
    earningsTodayUsd: 0,
  },
];

// Helper to pick items by restaurant for quick menus
export function getMenuForRestaurant(restaurantId: string): MenuItem[] {
  return menuItems.filter((m) => m.restaurantId === restaurantId);
}

