-- Milestone 1 ("nothing fake, nothing broken") — additive only.
-- 1) Checkout now collects a phone number and rider instructions.
-- 2) Every restaurant gets a full menu (6-8 dishes). Photos live in public/images
--    (freely licensed, credited in public/images/CREDITS.md and on /credits).
-- Safe to re-run: columns use IF NOT EXISTS, dishes use ON CONFLICT DO NOTHING.
-- Existing orders, users and dishes are not modified.

alter table public.orders add column if not exists customer_phone text;
alter table public.orders add column if not exists address_notes text;

insert into public.menu_items (id,restaurant_id,name,description,price_usd,available,image_url,cuisine_tag)
values
  ('mi_kfc_3','rest_kfc_gombe','Twister Wrap','Tortilla, filets de poulet croustillants, crudités et sauce',6.00,true,'/images/mi_kfc_3.jpg','Fast Food'),
  ('mi_kfc_4','rest_kfc_gombe','Ailes épicées (6 pcs)','Ailes de poulet épicées et croustillantes',6.00,true,'/images/mi_kfc_4.jpg','Poulet'),
  ('mi_kfc_5','rest_kfc_gombe','Bouchées de poulet croustillant','Petits morceaux de poulet pané, sauce au choix',5.00,true,'/images/mi_kfc_5.jpg','Poulet'),
  ('mi_kfc_6','rest_kfc_gombe','Frites (grande portion)','Frites dorées et salées',2.50,true,'/images/mi_kfc_6.jpg','Accompagnement'),
  ('mi_pili_3','rest_pili_pili','Poulet braisé pili pili','Demi-poulet mariné, braisé au charbon, piment maison',10.00,true,'/images/mi_pili_3.jpg','Grillades'),
  ('mi_pili_4','rest_pili_pili','Ntaba (chèvre grillée)','Viande de chèvre grillée, oignons et piment',9.00,true,'/images/mi_pili_4.jpg','Grillades'),
  ('mi_pili_5','rest_pili_pili','Makemba frits','Bananes plantains frites',3.00,true,'/images/mi_pili_5.jpg','Accompagnement'),
  ('mi_pili_6','rest_pili_pili','Chikwangue','Pain de manioc traditionnel',1.50,true,'/images/mi_pili_6.jpg','Accompagnement'),
  ('mi_pili_7','rest_pili_pili','Primus 72 cl','Bière blonde congolaise',2.50,true,'/images/mi_pili_7.jpg','Boisson'),
  ('mi_flore_2','rest_chez_flore','Poulet à la moambe','Poulet mijoté dans la sauce noix de palme',9.00,true,'/images/mi_flore_2.jpg','Congolais'),
  ('mi_flore_3','rest_chez_flore','Liboke de poisson','Poisson cuit en feuilles de bananier, épices',11.00,true,'/images/mi_flore_3.jpg','Congolais'),
  ('mi_flore_4','rest_chez_flore','Fumbwa','Feuilles de fumbwa à l''arachide et au poisson fumé',7.00,true,'/images/mi_flore_4.jpg','Congolais'),
  ('mi_flore_5','rest_chez_flore','Madesu','Haricots rouges mijotés à la tomate',4.00,true,'/images/mi_flore_5.jpg','Congolais'),
  ('mi_flore_6','rest_chez_flore','Fufu','Pâte de manioc et maïs',1.50,true,'/images/mi_flore_6.jpg','Accompagnement'),
  ('mi_flore_7','rest_chez_flore','Jus de bissap','Infusion d''hibiscus maison, bien fraîche',2.00,true,'/images/mi_flore_7.jpg','Boisson'),
  ('mi_bistrot_2','rest_bistrot','Croque-monsieur','Jambon, emmental, béchamel, salade verte',7.00,true,'/images/mi_bistrot_2.jpg','Bistrot'),
  ('mi_bistrot_3','rest_bistrot','Salade César','Poulet grillé, parmesan, croûtons, sauce César',9.00,true,'/images/mi_bistrot_3.jpg','Bistrot'),
  ('mi_bistrot_4','rest_bistrot','Burger du Bistrot','Bœuf haché, cheddar, oignons caramélisés, frites',12.00,true,'/images/mi_bistrot_4.jpg','Bistrot'),
  ('mi_bistrot_5','rest_bistrot','Filet de capitaine','Capitaine poêlé, sauce beurre citronné, riz',16.00,true,'/images/mi_bistrot_5.jpg','Poisson'),
  ('mi_bistrot_7','rest_bistrot','Crème brûlée','Crème vanille, caramel croquant',5.00,true,'/images/mi_bistrot_7.jpg','Dessert'),
  ('mi_poulet_2','rest_maison_poulet','Poulet entier braisé','Poulet entier braisé, pour 3 à 4 personnes',20.00,true,'/images/mi_poulet_2.jpg','Poulet'),
  ('mi_poulet_3','rest_maison_poulet','Ailes de poulet grillées (8 pcs)','Ailes marinées, grillées au feu de bois',7.00,true,'/images/mi_poulet_3.jpg','Poulet'),
  ('mi_poulet_4','rest_maison_poulet','Brochettes de poulet','Trois brochettes, oignons et poivrons',7.00,true,'/images/mi_poulet_4.jpg','Poulet'),
  ('mi_poulet_5','rest_maison_poulet','Frites de manioc','Manioc frit croustillant',3.00,true,'/images/mi_poulet_5.jpg','Accompagnement'),
  ('mi_poulet_6','rest_maison_poulet','Riz blanc','Riz parfumé nature',2.00,true,'/images/mi_poulet_6.jpg','Accompagnement'),
  ('mi_pizza_3','rest_pizza_inn','Pizza Pepperoni (M)','Sauce tomate, mozzarella, pepperoni',11.00,true,'/images/mi_pizza_3.jpg','Pizza'),
  ('mi_pizza_4','rest_pizza_inn','Pizza Quatre fromages (M)','Mozzarella, gorgonzola, parmesan, chèvre',12.00,true,'/images/mi_pizza_4.jpg','Pizza'),
  ('mi_pizza_5','rest_pizza_inn','Pizza Végétarienne (M)','Poivrons, champignons, oignons, olives',10.00,true,'/images/mi_pizza_5.jpg','Pizza'),
  ('mi_pizza_6','rest_pizza_inn','Pizza Hawaïenne (M)','Jambon, ananas, mozzarella',11.00,true,'/images/mi_pizza_6.jpg','Pizza'),
  ('mi_pizza_7','rest_pizza_inn','Pain à l''ail','Pain grillé, beurre à l''ail et persil',4.00,true,'/images/mi_pizza_7.jpg','Accompagnement'),
  ('mi_fuego_1','rest_fuego','Entrecôte grillée','Entrecôte 300 g, frites maison, sauce poivre',18.00,true,'/images/mi_fuego_1.jpg','Grillades'),
  ('mi_fuego_2','rest_fuego','Brochettes mixtes','Bœuf, poulet et saucisse, légumes grillés',10.00,true,'/images/mi_fuego_2.jpg','Grillades'),
  ('mi_fuego_3','rest_fuego','Côtelettes d''agneau','Quatre côtelettes, romarin, pommes sautées',17.00,true,'/images/mi_fuego_3.jpg','Grillades'),
  ('mi_fuego_4','rest_fuego','Poulet grillé au citron','Demi-poulet mariné citron et ail',11.00,true,'/images/mi_fuego_4.jpg','Poulet'),
  ('mi_fuego_5','rest_fuego','Tilapia braisé','Tilapia entier braisé, oignons, piment',13.00,true,'/images/mi_fuego_5.jpg','Poisson'),
  ('mi_fuego_6','rest_fuego','Saucisses grillées','Saucisses de bœuf grillées, moutarde',7.00,true,'/images/mi_fuego_6.jpg','Grillades'),
  ('mi_fuego_7','rest_fuego','Maïs grillé','Épis de maïs grillés au charbon',2.50,true,'/images/mi_fuego_7.jpg','Accompagnement'),
  ('mi_orient_1','rest_orient','Nouilles sautées au poulet','Nouilles de blé, poulet, légumes, sauce soja',9.00,true,'/images/mi_orient_1.jpg','Asiatique'),
  ('mi_orient_2','rest_orient','Riz cantonais','Riz sauté, œuf, petits pois, jambon',8.00,true,'/images/mi_orient_2.jpg','Asiatique'),
  ('mi_orient_3','rest_orient','Nems (6 pcs)','Rouleaux croustillants au porc, sauce aigre-douce',6.00,true,'/images/mi_orient_3.jpg','Asiatique'),
  ('mi_orient_4','rest_orient','Poulet Général Tao','Poulet croustillant, sauce sucrée-épicée, riz',11.00,true,'/images/mi_orient_4.jpg','Asiatique'),
  ('mi_orient_5','rest_orient','Bœuf sauté aux oignons','Émincé de bœuf, oignons, gingembre',12.00,true,'/images/mi_orient_5.jpg','Asiatique'),
  ('mi_orient_6','rest_orient','Soupe wonton','Raviolis aux crevettes dans un bouillon clair',7.00,true,'/images/mi_orient_6.jpg','Asiatique'),
  ('mi_orient_7','rest_orient','Crevettes sautées à l''ail','Crevettes, ail, piment doux, riz',14.00,true,'/images/mi_orient_7.jpg','Asiatique'),
  ('mi_mamba_1','rest_mamba','Pondu au poisson salé','Feuilles de manioc pilées, makayabu, huile de palme',8.00,true,'/images/mi_mamba_1.jpg','Congolais'),
  ('mi_mamba_2','rest_mamba','Poulet mwambe','Poulet fermier en sauce moambe, riz',10.00,true,'/images/mi_mamba_2.jpg','Congolais'),
  ('mi_mamba_3','rest_mamba','Liboke de capitaine','Capitaine en papillote de feuilles de bananier',13.00,true,'/images/mi_mamba_3.jpg','Poisson'),
  ('mi_mamba_5','rest_mamba','Ngulu (porc braisé)','Porc braisé, piment et oignons',10.00,true,'/images/mi_mamba_5.jpg','Congolais'),
  ('mi_mamba_6','rest_mamba','Kwanga','Pain de manioc fermenté',1.50,true,'/images/mi_mamba_6.jpg','Accompagnement'),
  ('mi_mamba_7','rest_mamba','Loso na madesu','Riz et haricots mijotés',4.00,true,'/images/mi_mamba_7.jpg','Congolais'),
  ('mi_baguette_1','rest_baguette','Croissant pur beurre','Croissant feuilleté du jour',1.50,true,'/images/mi_baguette_1.jpg','Boulangerie'),
  ('mi_baguette_2','rest_baguette','Pain au chocolat','Viennoiserie au chocolat',2.00,true,'/images/mi_baguette_2.jpg','Boulangerie'),
  ('mi_baguette_3','rest_baguette','Baguette tradition','Baguette croustillante cuite sur place',1.00,true,'/images/mi_baguette_3.jpg','Boulangerie'),
  ('mi_baguette_4','rest_baguette','Sandwich jambon-beurre','Baguette, jambon, beurre',4.00,true,'/images/mi_baguette_4.jpg','Sandwich'),
  ('mi_baguette_5','rest_baguette','Sandwich poulet crudités','Poulet, salade, tomate, mayonnaise',5.00,true,'/images/mi_baguette_5.jpg','Sandwich'),
  ('mi_baguette_7','rest_baguette','Quiche lorraine','Part de quiche lardons et fromage',4.50,true,'/images/mi_baguette_7.jpg','Boulangerie'),
  ('mi_baguette_8','rest_baguette','Café au lait','Café arabica et lait chaud',2.50,true,'/images/mi_baguette_8.jpg','Boisson'),
  ('mi_sushi_1','rest_sushi','Plateau mixte (18 pcs)','Makis, california et nigiris assortis',25.00,true,'/images/mi_sushi_1.jpg','Sushi'),
  ('mi_sushi_2','rest_sushi','California roll (8 pcs)','Surimi, avocat, concombre, sésame',10.00,true,'/images/mi_sushi_2.jpg','Sushi'),
  ('mi_sushi_3','rest_sushi','Maki saumon (6 pcs)','Saumon frais, riz vinaigré, nori',7.00,true,'/images/mi_sushi_3.jpg','Sushi'),
  ('mi_sushi_4','rest_sushi','Sashimi saumon (8 pcs)','Tranches de saumon frais',14.00,true,'/images/mi_sushi_4.jpg','Sushi'),
  ('mi_sushi_5','rest_sushi','Nigiri assortis (6 pcs)','Saumon, thon et crevette',12.00,true,'/images/mi_sushi_5.jpg','Sushi'),
  ('mi_sushi_6','rest_sushi','Tempura de crevettes','Crevettes en beignet léger, sauce tentsuyu',11.00,true,'/images/mi_sushi_6.jpg','Sushi'),
  ('mi_sushi_7','rest_sushi','Soupe miso','Tofu, wakamé, ciboule',4.00,true,'/images/mi_sushi_7.jpg','Sushi'),
  ('mi_sushi_8','rest_sushi','Edamame','Fèves de soja, fleur de sel',4.00,true,'/images/mi_sushi_8.jpg','Sushi'),
  ('mi_regal_1','rest_regal','Mbisi ya kalinga','Poisson braisé entier, sauce tomate pimentée',12.00,true,'/images/mi_regal_1.jpg','Poisson'),
  ('mi_regal_2','rest_regal','Poulet à la moambe','Poulet en sauce noix de palme, riz ou fufu',10.00,true,'/images/mi_regal_2.jpg','Congolais'),
  ('mi_regal_4','rest_regal','Fumbwa aux crevettes','Fumbwa, pâte d''arachide, crevettes séchées',8.00,true,'/images/mi_regal_4.jpg','Congolais'),
  ('mi_regal_5','rest_regal','Chèvre en sauce','Ragoût de chèvre tomate et oignons',10.00,true,'/images/mi_regal_5.jpg','Congolais'),
  ('mi_regal_6','rest_regal','Bananes plantains braisées','Plantains mûrs grillés au charbon',3.00,true,'/images/mi_regal_6.jpg','Accompagnement'),
  ('mi_regal_7','rest_regal','Jus de maracuja','Fruit de la passion pressé',2.00,true,'/images/mi_regal_7.jpg','Boisson')
on conflict (id) do nothing;
